#!/bin/sh
#/usr/local/bin/wspell
# a script to spell a word
# by daa 1-11-98
# usage:
# " wspell "
# or
# " wspell <first_letters_of_word> "
# or
# " wspell <first_letters_of_word> <second_input_of_a_portion_word> "

noact () {
echo -n " No action taken... Hit <ENTER> "
read hit
}

if test -z  $1
then
echo -n "
 Enter the First few characte(s) of your word
 As in the \"var\" in \" variable\": "
 read word
else
word=$1
fi
case $word in
"") : noact
 ;;
#
*) :
if test -z $2
then
echo -n "
 Enter a few letters in the word ( Entries are Not required )
 As in the \"abl\" in \"variable\": "
read few
case $few in
"") :
 look $word | less
;;
#
*) :
 look $word | grep $few | less
 ;;
#
esac
else
few=$2
look $word | grep $few | less
fi
;;
#
esac
exit 0
# End of File

