all: libexampleecho.so

CFLAGS = -D_REENTRANT -fPIC -DPIC -Wall -ggdb


libexampleecho.so: exampleecho.o
	$(CC) -shared  exampleecho.o -Wl,-soname -Wl,libexampleecho.so \
	-o libexampleecho.so -lxmms `glib-config --libs` \
	`gtk-config --libs` -ggdb
	chmod 644 libexampleecho.so
	cp libexampleecho.so ~/.xmms/Plugins/

exampleecho.o: exampleecho.c
	$(CC) -c $(CFLAGS) `glib-config --cflags` \
	`gtk-config --cflags` exampleecho.c -ggdb

.PHONY: clean

clean:
	-rm exampleecho.o libexampleecho.so