all: msg_test msg_test2

OBJS=    msgq.o\
         syscall_stuff.o
CC=gcc
CFLAGS=-c -g
LIBS=-lpthread

%.o:%.c
	${CC} ${CFLAGS} $^

msg_test: ${OBJS}
	${CC} -o $@ $^ ${LIBS}

msg_test2: msgq2.o syscall_stuff.o
	${CC} -o $@ $^ ${LIBS}

clean:
	rm -f msg_test msg_test2 *.o
