
INCLUDEDIR = /usr/src/linux/include

CFLAGS = -c  -D__KERNEL__ -DMODULE -O -Wall -I$(INCLUDEDIR)



VER = $(shell awk -F\" '/REL/ {print $$2}' $(INCLUDEDIR)/linux/version.h)

OBJS = myaudio.o

all: 	$(OBJS)

myaudio.o:
	cc $(CFLAGS) myaudio.c	

install:
	install -c myaudio.o 

clean:
	rm -f myaudio.o core











