#!/bin/sh
#
# program:	popcheck	4 aug 1995
# descript:	periodically checks my mail on the POP Server while a 
#		PPP connection is up.
#
# First, some variables
PopServer=ctrvax.vanderbilt.edu
Name=myname
Password=mypassword
MailFolder=/root/mail/mail-in

# Now, make sure the PPP PID file is extant
while [ -e "/var/run/ppp0.pid" ]	
do
	sleep 15m
	if [ -e "/var/run/ppp0.pid" ]; then
		popclient -3 -u $Name -p $Password -o $MailFolder $PopServer
	fi
done
exit 0
