#!/bin/sh
case "$1" in
	start) # Start daemons.
		echo "Starting lpd: \c"; /usr/local/bin/lpd; echo;
		;;
	stop) # Stop daemons.
		echo "Shutting down lpd: \c"
		server=`/usr/local/bin/lpc -Pany@localhost lpd \
		| awk '{for(i=1;i<=NF;++i){v=$i+0;if(v>1){ print v;exit;}}}'`
		if [ -n "$server" ]; then
			echo " server pid $server";
			kill $server;
		else
			echo " no server active";
		fi;
		;;
	*)
		echo "Usage: lpd {start|stop}"
		exit 1
		;;
esac
