#!/bin/sh
# Hacked together by I. Burger
# gpf@pikkedil.energie.sun.ac.za

# I borrowed this from smbprint, this gets some information from .config

config_file=$THISDIR/.config

eval `cat $config_file`

# The trailing '-' makes nprint read from stdin, it should work without the
# minus, but this is just to be sure.  Use the top line to figure out errors,
# believe me, I had plenty, some of them really weird...

#(/usr/bin/nprint -S $SERVER -U $user -P $password -q $QUEUE -) 2> /tmp/nw-error
/usr/bin/nprint -S $server -U $user -P $password -q $queue -

# This line is extremely useful, see the README file.

# cat > /tmp/printout.ps
# chmod 644 /tmp/printout.ps

exit 0
