#! /bin/sh
# skeleton	example file to build /etc/init.d/ scripts.
#		This file should be used to construct scripts for /etc/init.d.
#
#		Written by Miquel van Smoorenburg <miquels@cistron.nl>.
#		Modified for Debian GNU/Linux
#		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
#
# Version:	@(#)skeleton  1.6  11-Nov-1996  miquels@cistron.nl
#
set -e

case "$1" in
  start)
    start-stop-daemon --start --verbose --pidfile /var/run/xterm.pid --exec /usr/bin/X11/X -- -quiet -indirect weber &
    ;;
  stop)
    start-stop-daemon --stop --verbose --pidfile /var/run/xterm.pid --exec /usr/bin/X11/X
    ;;
  reload)
    # echo "Reloading $NAME configuration files"
    # start-stop-daemon --stop --signal 1 --quiet --pidfile /var/run/$NAME.pid --exec $DAEMON
    ;;
  *)
    # echo "Usage: /etc/init.d/$NAME {start|stop|reload}"
    echo "Usage: /etc/init.d/xterm {start|stop}"
    exit 1
    ;;
esac

exit 0
